
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xzrirerkryrnkergvzyk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh6cmlyZXJrcnlybmtlcmd2enlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0Nzc1MjYsImV4cCI6MjA2MzA1MzUyNn0.gtEjv1VSRj3_cohOdJoZIrHJTtjxO_bH8pM34_CGPCY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
